### ISSUE TITLE
Any problem in build process triggers "No valid MSBuild was detected for the selected target:" exception

### ISSUE THREAD

**Issue by janpio** [apache/cordova-windows#266]
After code restructuring this Exception is triggered a bit too often.

E.g. if just the `build` process in MSBuild fails:

> CordovaError: No valid MSBuild was detected for the selected target: Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe: Command failed with exit code 1

This issue refers to a problem in the way the code is structured - returning an exception that is not 100% correct all the times.

**Comment by janpio** [comment]
Which one exactly? 

This issue refers to a problem in the way the code is structured - returning an exception that is not 100% correct all the times.

**Comment by vincent-at-684857612710** [comment]
I get the above mentioned error whenever i run cordova build windows

I have uninstalled Cordova and installed previous version where linux, windows and windows phone were supported..

I tried command on mac and windows.

**Comment by shazron** [comment]
Essentially the MSBuild detection code does not work well with VS 2017. Duping this into #274

**Comment by janpio** [comment]
The original issue was another problem - _any_ problem in the build process triggers this error message.

**Comment by janpio** [comment]
For future reference, this is the offending code:
https://github.com/apache/cordova-windows/blob/c52b81c3f6daff69b57939fcf62451d3c2a602dd/template/cordova/lib/build.js#L63-L85
