### ISSUE TITLE
Visual Studio and other requirements error messages are not optimal

### ISSUE THREAD

**Issue by janpio** [apache/cordova-windows#267]
When these were created it was only VS2013 and VS2015, Windows 10 also was not a thing. Because of this the error message of the requirement checks in multiple places output quite confusing instruction on what to do or install.

Unfortunately what to actually do is really complicated and so not easy to fix.

**Comment by brodybits** [comment]
Do you think this issue would persist if we would remove Windows 8.1 / Windows Phone 8.1 support, maybe drop support for VS2013/VS2015?

**Comment by janpio** [comment]
That would probably change the situation a bit, yes. If I remember correctly Win10 builds are only supported from VS15, but we would have to check this again first.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
