### ISSUE TITLE
Windows Platform Guide link is directed to Page Not Found

### ISSUE THREAD

**Issue by nandavelugoti** [apache/cordova-windows#268]
The below link for 'Windows Platform Guide' in README.md is leading to Page Not Found (404),
http://cordova.apache.org/docs/en/latest/guide/platforms/win8/index.html

**Comment by nandavelugoti** [comment]
This issue persists in the documentation site as well.

**Comment by janpio** [comment]
Hm, thanks for reporting.

This is a result of changing the path of the file from `win8` to `windows`.

Here is the current version of that document if you are still looking for it: http://cordova.apache.org/docs/en/dev/guide/platforms/windows/index.html

I will now try to find a solution :/

**Comment by nandavelugoti** [comment]
Ok Thanks.

**Comment by janpio** [comment]
Should be hotfixed for now:
https://cordova.apache.org/docs/en/latest/guide/platforms/win8/index.html

**Comment by DennisSmolek** [comment]
Broken again....

**Comment by janpio** [comment]
What exactly is broken? Working for me right now.

**Comment by DennisSmolek** [comment]
@janpio at the time of writing going to your link took me to a white page, also the links in the bar were broken. Seems ok now
