### ISSUE TITLE
description tag set to default instead of defined value - regression from 5.0.0

### ISSUE THREAD

**Issue by mobidev111** [apache/cordova-windows#270]
The `<description>` tag is set to a default value instead of the in the config.xml defined value. This is is a regression from cordova-windows 5.0.0.

### situation
macOS host machine
cordova-lib: 8.1.0
cordova-windows 6.0.0

A description is correctly set in config.xml:

config.xml
```
  <description>
    Demo
  </description>
```

when running on a mac (or windows):
```
cordova prepare
```

### actual

platforms/windows/config.xml contains an additional description tag (with default content), in addition to the customized description tag
```
  <description>
    A sample Apache Cordova application that responds to the deviceready event.
  </description>
  [...]
  <description>
    Demo
  </description>
```

The appxmanifest files contain only the default value instead of the set custom value:
`platforms/windows/package.phone.appxmanifest`
`platforms/windows/package.windows.appxmanifest`
`platforms/windows/package.windows10.appxmanifest`
```
-        <Description>Demo</Description>
+        <Description>A sample Apache Cordova application that responds to the deviceready event.</Description>
```
```
-            <m2:VisualElements Description="Demo" DisplayName="Demo">
+            <m2:VisualElements Description="A sample Apache Cordova application that responds to the deviceready event." DisplayName="Demo">
```
### expected

the correctly set description tag gets propagated.

### conditions

* happens only with cordova-windows 6.0.0 - doesn't happen when using cordova-windows 5.0.0 with an otherwise unchanged setup

* happens on mac & windows - however this a serious problem, as the generated code could be committed by mistake

* probable cause: in 6.0.0 the `platforms/windows/cordova/defaults.xml` contains a default value for the desciption tag for the first time.

The wrong description value comes form the defaults.xml, however the `<name>` and `<author>` tags get processed correctly:
`platforms/windows/cordova/defaults.xml`
```
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
```

**Comment by janpio** [comment]
Thanks for reporting this.

I updated your post so that the "tags" you included in your normal sentences are showing.

Will look into this, definitely not an intentional change.

**Comment by janpio** [comment]
First question: What file are you referring to with "defaults.xml"? 

I can only find https://github.com/apache/cordova-windows/blob/master/template/Properties/Default.rd.xml here in the repo which does not contain a description.

**Comment by mobidev111** [comment]
post updated, happens as well on windows. 

to reproduce: set a `<description>` tag in config.xml

**Comment by janpio** [comment]
How are you creating your project? Is this an existing or a new one? 

Investigation note to self: There was a change to the template config.xml to make it work with the `prepare` script for e2e testing: https://github.com/apache/cordova-windows/blame/20ed375676ff4dc7b772b40a7f18455a650a2028/template/config.xml This added a description here. From the looks of it this could be connected.

**Comment by mobidev111** [comment]
Just verified - happens as well with fresh project with `cordova create`.

The wrong content definitely comes from `platforms/windows/cordova/defaults.xml` - this files gets inconsistently handled - <description> gets the wrong treatment, but <name> and <author> tags work.

**Comment by wifisher** [comment]
I think that the issue here is that two description tags end up in platforms/windows/config.xml.

The first one is what appears to be copied to the Windows manifest file.

This is reproducible by creating a new project, editing the description in the project config.xml file and then adding the windows platform.

**Comment by janpio** [comment]
Thanks @wifisher for the investigation, so the addition of the [template config.xml](https://github.com/apache/cordova-windows/blame/20ed375676ff4dc7b772b40a7f18455a650a2028/template/config.xml) messed with the generated file and the wrong value is chosen :/ Will have to look further into this where something goes wrong... maybe the value should be replaced instead of written? Or it should be smarter selecting the one to use?

**Comment by wifisher** [comment]
I think that the description from the toplevel project config.xml file should simply replace the one in platforms/windows/config.xml. I don't personally think that anything more complicated then that is required.

**Comment by janpio** [comment]
Reproduced.

On changing `config.xml`'s description, `platforms/windows/config.xml` gets this diff:

```diff
-   <name>HelloCordova</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
+   <name>HelloCordova</name>
+   <description>
+       Our new description.
+   </description>
```

and nothing else in the native project changes.

**Comment by janpio** [comment]
Ok, looked into this and this `updateConfigFilesFrom` method is something that follows a pattern in _all_ Cordova platforms (with some customization), and the Windows one is similar to iOS and Android in how it does the merging. Meaning: The behavior here of this method is correct (enough).

What is not correct, is that a file that already contains the description was used in the first step, in this case the `config.xml` which I modified for https://github.com/apache/cordova-windows/pull/254/files#diff-83c0809a5a3967aec365d13bf70b2be3. That change allowed the prepare script to work properly, but broke the logic from the method above as I didn't also create a `defaults.xml` file at the same time that was empty and that then would have been used as the initial template to build a config.xml from.

I created a PR to fix this: https://github.com/apache/cordova-windows/pull/335

**Comment by janpio** [comment]
If you need a workaround now, you can copy this file https://github.com/apache/cordova-windows/pull/335/files#diff-2d896ba8e3f9fc0921e0e059c5f2d5d9 to `platforms/windows/cordova/defaults.xml` in your project. Then the config.xml creation process should work correctly.

**Comment by wifisher** [comment]
Thanks @janpio for looking into and resolving this issue.

**Comment by janpio** [comment]
Sorry it took so long, this issue just got forgotten :/
