### ISSUE TITLE
npm install -g cardova not working

### ISSUE THREAD

**Issue by ambarnigade** [apache/cordova-windows#271]
getting following error
tried all possible options - npm set registry https //registry.npmjs.org/ . installed Git

tried checking - https://registry.npmjs.org/cardova/cordova/ nothing exists at this location

ERROR -->
npm ERR! code E404
npm ERR! 404 Not Found: cordova@latest

npm ERR! A complete log of this run can be found in:

**Comment by shazron** [comment]
Try `cordova`, instead of `cardova`

**Comment by ambarnigade** [comment]
my bad, its a typo in the issue. i have been trying cordova 

do i need to install ant? i have installed Git

**Comment by ambarnigade** [comment]
was able to resolve the issue. 
following were the errors
1. PATH for C:\Program Files\Git\bin was not set. earlier path was C:\Program Files\Git. it was still not working
2. npm set registry https://registry.npmjs.org

thanks
