### ISSUE TITLE
MsBuild Tool not found

### ISSUE THREAD

**Issue by TheProgrammer2** [apache/cordova-windows#272]
I had a problem with the MSBuild Tool for building an ionic project for windows.
The reason for the problem might be that I have installed both, Visual Studio Professional 2017 and Visual Studio Community 2017.

After adding the windows platform with `cordova platform add windows@6.0.0` I got the following output when trying to compile with `ionic cordova build windows`:

```
Building project: C:\Users\Lukas\Desktop\Schulapp\Schulapp\platforms\windows\CordovaApp.Windows10.jsproj
        Configuration : debug
        Platform      : anycpu
        Buildflags    : /p:AppxBundle=Never
        MSBuildTools  : C:\Program Files (x86)\MSBuild\14.0\bin
buildProject spawn: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild [ 'C:\\Users\\Lukas\\Desktop\\Schulapp\\Schulapp\\platforms\\windows\\CordovaApp.Windows10.jsproj',
  '/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal',
  '/nologo',
  '/p:Configuration=debug',
  '/p:Platform=anycpu',
  '/p:AppxBundle=Never' ] { stdio: 'inherit' }
C:\Users\Lukas\Desktop\Schulapp\Schulapp\platforms\windows\CordovaApp.Windows10.jsproj(61,5): error MSB4019: Das importierte Projekt "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Micr
osoft.VisualStudio..Default.props" wurde nicht gefunden. Vergewissern Sie sich, dass der Pfad in der <Import>-Deklaration korrekt und die Datei auf dem Datenträger vorhanden ist.
(node:9196) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): code: Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe: Command failed with exit code 1 No valid MSBuild was detected for the selected target: Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe: Command failed with exit code 1
```

This line 61 says:
```
<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\$(WMSJSProjectDirectory)\Microsoft.VisualStudio.$(WMSJSProject).Default.props" />
```

`Ionic info` says:
```
cli packages: (C:\Users\Lukas\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : windows 6.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.11.5
    npm  : 3.10.10
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

```
`cordova platform list` says:
```
Installed platforms:
  windows 6.0.0
Available platforms:
  android ~7.0.0
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  www ^3.12.0
```

After adding the environment variable MSBUILDDIR to `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin` it worked.

For additional information and the complete solution path please look at https://forum.ionicframework.com/t/windows-10-sdk-missing/126215/12

**Comment by janpio** [comment]
Hi again :)

The actual reason for this not working is probably that the MSBuild selection code somehow chose `C:\Program Files (x86)\MSBuild\14.0\bin`. Why is speculation, my guess was that the existance of both VS17 installations caused some confusion. But might be something totally unrelated as well.

Steps to fix this:
1. Reproduce the problem.
2. Add debug output to the MSBuildTools selection to udnerstand what is going on.
3. Fix it.

**Comment by shazron** [comment]
Essentially the MSBuild detection code does not work well with VS 2017. Duping this into #274
