### ISSUE TITLE
cordova build windows generates following error "Error: No valid MSBuild was detected for the selected target."

### ISSUE THREAD

**Issue by vincent-at-684857612710** [apache/cordova-windows#273]
cordova platform list
Installed platforms: browser 5.0.3, ios 4.5.4, osx 4.0.1, windows 5.0.0
Available platforms: amazon-fireos, android, blackberry10, firefoxos, webos

cordova -v
5.4.0

I have tried this on Mac High Sierra as well as Windows 10

**Comment by janpio** [comment]
Uh - current `cordova` version is 8.0.0 and current `cordova-windows` is 6.0.0 - you should try updating both. (Instructions here for example: https://ionic.zone/cordova/update)

**Comment by AngelCareaga** [comment]
My **temporary** solution has been only to execute it in debug mode and not in release mode.

At the time of generating the compiled for the store does not happen, it works perfectly. I will continue to see the same log to see what is happening.

**Comment by shazron** [comment]
Essentially the MSBuild detection code does not work well with VS 2017. Duping this into #274
