### ISSUE TITLE
cordova-windows doesn't support portrait splashscreens in Windows 10 Mobile?

### ISSUE THREAD

**Issue by Kuzdo** [apache/cordova-windows#275]
Hi,

Firstly, sorry for my English.

Am I blind or cordova-windows doesn't support portrait splashscreens in Windows 10 Mobile?
This table: ![image](https://user-images.githubusercontent.com/6685335/40542394-46822b92-6020-11e8-807d-80620e96cbc1.png) shows me, that only valid splashscreens for Windows 10 Mobile are in landscape mode.

Or maybe I don't know about something?

Regards.

**Comment by janpio** [comment]
To be able to maybe investigate: Where is this table from?

**Comment by Kuzdo** [comment]
Here: https://github.com/apache/cordova-plugin-splashscreen#windows-specific-information

**Comment by janpio** [comment]
Ah, then this here is the wrong location to post this. This issue tracker is only for `cordova-windows` itself.
That plugin is still handled at JIRA: https://issues.apache.org/jira/projects/CB/issues
