### ISSUE TITLE
Can I build and run windows platform with device or simulator flag in mac os?

### ISSUE THREAD

**Issue by sudotamm** [apache/cordova-windows#276]
I want to dev windows mobile in mac os. So I create windows platform with command 'cordova platform add windows', but when I try to build or run with  command 'cordova build/run windows', It will failed with error 'No valid MSBuild was detected for the selected target.'

Visual studio 2017 for mac is installed and added dotnet and msbuild to environment path.
Cordova (Cordova CLI) : 8.0.0 
Cordova Platforms : ios 4.5.4 windows 6.0.0
OS: macOS High Sierra
Xcode : Xcode 9.4.1 Build version 9F2000

**Comment by janpio** [comment]
Uh, I don't think anyone ever tried that. 

You might want to try the environment variables mentioned in this blog post: https://cordova.apache.org/announcements/2018/02/27/cordova-windows-6.0.0.html

**Comment by sudotamm** [comment]
@janpio 
I add MSBUILDDIR variable and try to build again. Failed with error "CordovaError: No valid MSBuild was detected for the selected target: Windows SDK not found. Ensure that you have installed Windows 10.0 SDK along with Visual Studio or install Windows 10.0 SDK separately from https://dev.windows.com/en-us/downloads".
Is that means windows 10.0 SDK must run with Windows 10 OS?

**Comment by janpio** [comment]
Very much possible, yes. I messed with that code (finding MSBuild) some time ago, and I am not sure if it was actually made for a non Windows environment. You will probably have to look at the code to figure that out (Best use the error messages you are getting to find the correct code parts).

**Comment by janpio** [comment]
Reading this again later: No, this just means that you have to have the Windows 10.0 SDK installed. It's very possible that this only _works_ on Windows of course.

**Comment by janpio** [comment]
I checked: https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk makes it clear that Windows 10 SDK can only be installed on Windows 10, and not on macOS or Linux.

Thus the response to your initial question is unfortunately: No, building, running and emulating a Cordova Windows app will only work on Windows.
