### ISSUE TITLE
Requirements check results for windows: Windows OS: not installed

### ISSUE THREAD

**Issue by ThaierAlkhateeb** [apache/cordova-windows#279]
I have already made ionic app and it works on android/ios
I just wanted to add windows platform and it added successfully .
but when I call
 C:\ionic2>cordova requirements
I got this 
Requirements check results for windows:
Windows OS: not installed
Error: getConfig(...).getWindowsTargetVersion is not a function
(node:932) UnhandledPromiseRejectionWarning: CordovaError: Some of requirements
check failed

I don't know where is the problem ,because I build the app but it doesn't instaled in the phone.

**Comment by janpio** [comment]
What cordova-windows version are you using?
What operating system are you using?

What is your `ionic info` output?

**Comment by ThaierAlkhateeb** [comment]
`
cli packages: (C:\Users\test\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : windows 6.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.3
    npm  : 3.10.10
    OS   : Windows 7

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
`

**Comment by ThaierAlkhateeb** [comment]
I did
`1) cordova platform add windows@6.0.0

2) cordova build windows -- --appx=8.1-phone`

I got a .sln file in platform/windows folder and output in platforms/windows/AppPackages folder.

but the output .appx file was too small (3.625 K) just like HellowWorld app with cordova icon.

Am I in the right way or did I messed up? How can I do that using VS2017

**Comment by janpio** [comment]
Windows 7 doesn't match the requirements of `cordova-windows`. You need 8.1 or 10.

**Comment by ThaierAlkhateeb** [comment]
I will try that .
Many thanks

**Comment by ThaierAlkhateeb** [comment]
My app right did build and run but  it runs an empty app it just like a HellowWorld app with a cordova splachscreen logo :(

**Comment by janpio** [comment]
Then seems it didn't copy over the app to the www folder of the platform.

Does emulating the app work?
What exact command are you using to build?

**Comment by ThaierAlkhateeb** [comment]
You are right the www folder is empty but my src folder contains every thing.
I used VS2017 to build my app.
And also tried that from command prompt using this command
cordova build windows --appx=10-phone
the same result

**Comment by ThaierAlkhateeb** [comment]
By the way it emulates and the output is too small(.appx ) and it just like hellowWorld app
it has only cordova icon in splachscreen then white screen

**Comment by ThaierAlkhateeb** [comment]
[https://ibb.co/jtNNcJ](url)

**Comment by ThaierAlkhateeb** [comment]
here is my output 
https://ibb.co/jtNNcJ

**Comment by ThaierAlkhateeb** [comment]
I really thank you .
It works right now ,I have made a new ionic project and copied the source and packages from my app to this and it works like a charm.
Liebe Grüße

**Comment by janpio** [comment]
Wunderbar. 

Awesome I could be of help :)
