### ISSUE TITLE
window.requestFileSystem

### ISSUE THREAD

**Issue by morkus** [apache/cordova-windows#283]
My project works fine on Android and Windows 10
But I've an issue with Win10 for accessing to the FileSystem

The project is configured with cordova-windows@6.0.0 and cordova-plugin-file@6.0.1
When I try to use window.requestFileSystem, it is always undefined.

Is there something specific to configure in config.xml or something like that ?

**Comment by janpio** [comment]
This is not really a `cordova-windows` question, but something that concerns `cordova-plugin-file`.

That being said, is `window.requestFileSystem` a thing the plugin adds or a general browser API? Should this API be available on Windows?

**Comment by janpio** [comment]
I just created a Cordova Windows app and added the file plugin:

```
E:\Projects\throwaway
λ cd cordovaWindowsFile\

E:\Projects\throwaway\cordovaWindowsFile  (helloworld@1.0.0)
λ cordova platform add windows
Using cordova-fetch for cordova-windows@^7.0.0
Adding windows project...
Creating Cordova Windows Project:
        Path: platforms\windows
        Namespace: io.cordova.hellocordova
        Name: HelloCordova

Windows project created with cordova-windows@7.0.0
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for windows
Adding cordova-plugin-whitelist to package.json

E:\Projects\throwaway\cordovaWindowsFile  (helloworld@1.0.0)
λ cordova plugin add cordova-plugin-file
Installing "cordova-plugin-file" for windows
Adding cordova-plugin-file to package.json

E:\Projects\throwaway\cordovaWindowsFile  (helloworld@1.0.0)
λ
```

When I ran it with `cordova run windows` and connected to the WebView with Microsoft Edge DevTools, I got this in the console:

![image](https://user-images.githubusercontent.com/183673/57249809-358d8700-7046-11e9-9991-b664c7a9c17b.png)

So I would say this works as intended.

If this doesn't help, please reply to this issue and I will be happy to reopen it.
