### ISSUE TITLE
Troubles with template/Properties/Default.rd.xml

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-windows#288]
Continuation of <https://github.com/apache/cordova-discuss/issues/106> which is now closed:

cordova-windows has suffered from the following issues with `template/Properties/Default.rd.xml` that was introduced in GH-228 ([CB-12499](https://issues.apache.org/jira/browse/CB-12499)):

- [CB-13834](https://issues.apache.org/jira/browse/CB-13834) - problem building with  build with params `--release --bundle --archs="x64 x86 arm"` on AppVeyor CI *which remains unsolved*
- ~~[CB-14224](https://issues.apache.org/jira/browse/CB-14224) - running `coho audit-license-headers -r windows` gives a message that `template/Properties/Default.rd.xml` is missing the license header~~ (already solved in GH-284 [master] and GH-285 [6.0.x patch])
- ~~[CB-14225](https://issues.apache.org/jira/browse/CB-14225) - misspelling in sample Namespace serialize attribute name (with solution in GH-286)~~

It is clear from [CB-12499](https://issues.apache.org/jira/browse/CB-12499) that `Default.rd.xml` was introduced to solve a problem but it is unfortunately the actual circumstances are not so clear to me. The following observations indicate to me that `Default.rd.xml` should only be needed in case of a project using C# which I think is not always the case:
- If I would try generating both a JavaScript UWP project and a C# UWP project then VS 2017 would only add `Properties/Default.rd.xml` in case of C#.
- [Microsoft / Windows-universal-samples](https://github.com/Microsoft/Windows-universal-samples) keeps its sample `Default.rd.xml` in a `cs` directory ([Microsoft / Windows-universal-samples / SharedContent / cs / Default.rd.xml](https://github.com/Microsoft/Windows-universal-samples/blob/master/SharedContent/cs/Default.rd.xml)

Given the observed troubles and what I think are limited circumstances of need I would like to propose that we remove `template/Properties/Default.rd.xml` at some point in the future, as a major release item, and support it in a plugin if needed.

**Comment by brodybits** [comment]
> - [CB-13834](https://issues.apache.org/jira/browse/CB-13834) - problem building with  build with params `--release --bundle --archs="x64 x86 arm"` on AppVeyor CI *which remains unsolved*

now reported in GH-290

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
