### ISSUE TITLE
One specific spec fails on AppVeyor with VS2017 

### ISSUE THREAD

**Issue by janpio** [apache/cordova-windows#290]
This test fails, although it shouldn't:

```
Failures:
1) Cordova create and build spec.6a should generate appxupload and appxbundle for Windows 10 project bundle release build
  Message:
    Expected 1 to be 3.
  Stack:
    Error: Expected 1 to be 3.
        at _expectExist (C:\projects\cordova-windows\spec\e2e\endtoend.spec.js:53:97)
        at UserContext.<anonymous> (C:\projects\cordova-windows\spec\e2e\endtoend.spec.js:243:9)
  Message:
    Expected 0 to be 1.
  Stack:
    Error: Expected 0 to be 1.
        at verifySubDirContainsFile (C:\projects\cordova-windows\spec\e2e\endtoend.spec.js:46:90)
        at _expectSubdirAndFileExist (C:\projects\cordova-windows\spec\e2e\endtoend.spec.js:60:9)
        at UserContext.<anonymous> (C:\projects\cordova-windows\spec\e2e\endtoend.spec.js:244:9)
19 specs, 1 failure
Finished in 271.36 seconds
```

Only happens on AppVeyor.

**Comment by brodybits** [comment]
It looks like this was reported in [CB-13834](https://issues.apache.org/jira/browse/CB-13834). Can we close [CB-13834](https://issues.apache.org/jira/browse/CB-13834) as a duplicate, migrated issue?

As discussed in GH-288 (#288) and in [CB-13834](https://issues.apache.org/jira/browse/CB-13834) it looks like this issue is a result of having added `template/Properties/Default.rd.xml`.

**Comment by janpio** [comment]
> It looks like this was reported in CB-13834. Can we close CB-13834 as a duplicate, migrated issue?

Closed with link to this issue.

**Comment by janpio** [comment]
Relevant SO question I had created: https://stackoverflow.com/questions/48771047/the-process-cannot-access-the-file-default-rd-xml-because-it-is-being-used-by

**Comment by janpio** [comment]
This was cleaned up a bit with this PR and the test is now disabled: https://github.com/apache/cordova-windows/pull/330

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
