### ISSUE TITLE
Scrolling not working on Windows App when Local Mode is enabled

### ISSUE THREAD

**Issue by dominic-simplan** [apache/cordova-windows#291]
Hello,
I have an application which needs to run in local mode. However, as soon as I enable local mode in the config.xml by setting `<preference name="WindowsDefaultUriPrefix" value="ms-appx://" />`, scrolling does not work anymore (scrollbar is also not displayed):
![grafik](https://user-images.githubusercontent.com/22240239/44145176-d8f055ee-a08a-11e8-89ee-fe0252450826.png)

Changing the mode back to Remote, and the scrolling works again.

Here is a repository with a simple example application:
https://github.com/dominic-simplan/cordova-scrolling

Is this a bug or am I missing some additional setting?

**Comment by janpio** [comment]
Did I understand correctly that just toggling that preference disables or enables the scrolling in the app?

**Comment by dominic-simplan** [comment]
@janpio yes exactly...

**Comment by dominic-simplan** [comment]
And I just realized that only in local mode (where the scrolling doesn't work), the JavaScript Console in Visual Studio 2017 shows the following line when starting the app (not always, but very often):

> CSP14312: Die Direktive script-src ms-appx: 'unsafe-eval' blob: in Host Defined Policy wurde durch eine Ressource verletzt: inline script. Die Ressource wird blockiert.

Not sure if this is related or an issue though.

**Comment by janpio** [comment]
It is definitely something I would investigate as it contains "ms-appx" in the error message string. Some security meta tag thing that blocks stuff?

**Comment by dominic-simplan** [comment]
I tried but Visual Studio doesn't show where this CSP violation is caused and also the directive is not coming from my index.html. Seems like it is dynamically added by the runtime during startup? 
So I am really clueless how to investigate this further...

**Comment by janpio** [comment]
This sounds like the English version of your error message:

```
CSP14312: Resource violated directive 'script-src ms-appx: data: 'unsafe-eval'' in Host Defined Policy: inline script. Resource will be blocked.
```
(which also shows that the German version is a terrible translation, where does the "blob" come from?)

Here at least are some people having the same problem: https://forums.adobe.com/thread/2229445

Spend some time googling for the error message, I am sure you will find some instructions to add some preferences or meta tags.

**Comment by dominic-simplan** [comment]
I don't think it's a translation issue, here is exactly the same error in English: https://stackoverflow.com/questions/51764412/ionic-documentviewer-in-uwp-windows-not-working?rq=1
`CSP14312: Resource violated directive ‘script-src ms-appx: 'unsafe-eval' blob:’ in Host Defined Policy: inline script. Resource will be blocked.`

I already tried a lot of possible combinations of CSPs, none of which worked and the error stays the same. I rather believe the UWP runtime adds this CSP rule dynamically when executing the app in local mode and this again causes issues when using Cordova-based frameworks or the WebView in general.

The question therefore seems to be: Why doesn't allow Microsoft unsafe-inline for the script-src and would it solve the scrolling issue...
Or: Where is Cordova using inline scripting and it is necessary?

**Comment by janpio** [comment]
> I don't think it's a translation issue, here is exactly the same error in English

Good catch, I didn't find this.

For all the rest: Sorry, no idea :/

**Comment by dominic-simplan** [comment]
Okay I just tried to added the directive `script-src ms-appx-web: 'unsafe-eval' blob:` to my index.html and switch the app to remote mode: I can also see the violation, but scrolling works fine.
So the scrolling issue doesn't seem to be related to the CSP violation (which possibly doesn't have any bad side effects).

To wrap it up:

- A CSP violation error due to inline script is displayed when running the UWP app in local mode as the runtime dynamically overwrites the script-src policy at runtime. It is unknown what's blocked exactly, but most likely unrelated to the scrolling issue
- Scrolling does not work when local mode is enabled.

Do you think I should check directly with Microsoft or the Cordova Core team? I have no clue how to continue analyzing this issue. We just recently migrated to Cordova. Before we were using Xamarin with a WebView for the same app and scrolling was working...

**Comment by janpio** [comment]
If you have contact at Microsoft, go for it - they should know a bit about it.

I am one of the random (and volunteer) people that make up the Cordova Core team - there are currently not too many people around that know much about `cordova-windows`. You might try mailnig the dev list or ask in the correct channel in Slack: https://cordova.apache.org/contact/

**Comment by dominic-simplan** [comment]
Hi,

I was able to recreate the scrolling issue with a plain JS UWP app, so it is not an issue with Cordova. Seems like on a UWP app running in local mode is is necessary to enable scrolling by setting the css overflow property. See also [this thread](https://social.msdn.microsoft.com/Forums/en-US/20fc3a14-fe70-4d8d-ab47-e63b21ff391d/uwphtml-scrolling-does-not-work-in-js-uwp-app-with-direct-access-to-windows-uwp-api?forum=wpdevelop) for more details.

I don't know the reason for the CSP violations yet, however they don't seem to cause any issues in the app. 

Thanks again for your help, I really appreciate your quick responses and suggestions!

Dominic
