### ISSUE TITLE
Cordova UWP Plugin with a UIElement

### ISSUE THREAD

**Issue by JonasLaux** [apache/cordova-windows#295]
Hey everyone ,
Currently i have a Cordova plugin and a UWP Class library. The library is using native UIElements for different UI workflows. Is there a way to display those UIElements? I read, that XAML views can't be displayed. Is there a workaround somehow?
Maybe we can put the WebView in the background in fire up a native View. If yes, how do we get the current page, like in Android (cordova.getActivity())?
Thanks in advance!

**Comment by janpio** [comment]
No, this is unfortunately not possible with Cordova Windows. 

The generated project is a "UWP Javascript" project (`.jsproj), where the whole app _is_ a webview, so you can't render anything behind oder above the main webview. All the APIs for XAML and related UI stuff are also just not available in this type of app.
