### ISSUE TITLE
Change build config options

### ISSUE THREAD

**Issue by FredGr** [apache/cordova-windows#297]
When I build for windows using the CLI I get the following messages

> λ cordova build windows
ENV var MSBUILDDIR is set C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
Building project: D:\M - AEROMETRIX\E - ProductDesign\G - Tablet\Cordova\AexPAD\platforms\windows\CordovaApp.Windows10.jsproj
        Configuration : debug
        Platform      : anycpu
        Buildflags    : /p:AppxBundle=Never
        MSBuildTools  : C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
buildProject spawn: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild [ 'D:\\M - AEROMETRIX\\E - ProductDesign\\G - Tablet\\Cordova\\AexPAD\\platforms\\windows\\CordovaApp.Windows10.jsproj',
  '/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal',
  '/nologo',
  '/p:Configuration=debug',
  '/p:Platform=anycpu',
  '/p:AppxBundle=Never' ] { stdio: 'inherit' }
  prebuild.js: Patching platform `10`**

How can I change the Configuration:debug; Paltform:anycpu and /nologo options ?

Thanks

**Comment by janpio** [comment]
This is the generated build command, I am not sure those specific options are configurable.

You will have to look at the code that generated that command - searching here in this repo for e.g. "anycpu" or "nologo" should bring you pretty far.

Why do you want to change these?

**Comment by janpio** [comment]
Now that I know more about Cordova Windows, I can respond - although we never header back from you:

> How can I change the Configuration:debug; Paltform:anycpu and /nologo options ?

- By using `--release` you get `/p:Configuration=release`
- The parameter `--archs` influences the `/p:Platform` value: `anycpu`, `arm`, `x86`, `x64` are valid values
- `/nologo` is always added as it ensure that MSBuild output is minimal

Does this answer your question?
