### ISSUE TITLE
Keyboard App Crashes

### ISSUE THREAD

**Issue by Dead96** [apache/cordova-windows#323]
# Bug Report

## Problem
Sometimes the keyboard makes the app crashes

### What is expected to happen?
The keyboard normally appears when you select an input to be filled

### What does actually happen?
The keyboard **NOT** appears and the entire app crashes

## Information
Related to issue #269

### Command or Code
n.d.

### Environment, Platform, Device
Tablet Samsung Galaxy Book SM-W728NZKAITV, Windows

### Version information
Cordova 6.3.1
Cordova Windows 4.4.2
Ionic 1.3.2

## Checklist
- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by janpio** [comment]
Hi @Dead96, Cordova Windows 4.4.2 is really old. Can you update to a newer version and report if you still encounter this problem?

**Comment by janpio** [comment]
Ping @Dead96

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
