### ISSUE TITLE
Ability to override TargetPlatformVersion via config.xml

### ISSUE THREAD

**Issue by MarkMaldaba** [apache/cordova-windows#332]
# Feature Request

## Motivation Behind Feature

The ````CordovaApp.Windows10.jsproj```` template file has a hard-coded ````TargetPlatformVersion````, which currently seems to be set to ````10.0.10240.0````:

````xml
  <PropertyGroup>
    <TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
    <TargetPlatformVersion>10.0.10240.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.10240.0</TargetPlatformMinVersion>
    <MinimumVisualStudioVersion>14.0</MinimumVisualStudioVersion>
    <UapDefaultAssetScale>100</UapDefaultAssetScale>
  </PropertyGroup>
````

However, when I try to build my project, which should target ````10.0.15063.0````, I get build failures as the wrong platform version is targeted and the SDK for this version is not available to Visual Studio:

````
D:\MyApp>cordova build windows --arch=x86
ENV var VSINSTALLDIR is set C:\Program Files (x86)\Programming\Microsoft Visual Studio 2017
Building project: D:\MyApp\platforms\windows\CordovaApp.Windows10.jsproj
        Configuration : debug
        Platform      : x86
        Buildflags    : /p:AppxBundle=Never
        MSBuildTools  : C:\Program Files (x86)\Programming\Microsoft Visual Studio 2017\MSBuild\15.0\Bin
buildProject spawn: C:\Program Files (x86)\Programming\Microsoft Visual Studio 2017\MSBuild\15.0\Bin\msbuild [ 'D:\\MyApp\\platforms\\windows\\CordovaApp.Windows10.jsproj',
  '/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal',
  '/nologo',
  '/p:Configuration=debug',
  '/p:Platform=x86',
  '/p:AppxBundle=Never' ] { stdio: 'inherit' }
C:\Program Files (x86)\Programming\Microsoft Visual Studio 2017\MSBuild\Microsoft\VisualStudio\v15.0\JavaScript\Microsoft.VisualStudio.JavaScript.UAP.targets(84,3): error : "
10.0.10240.0" is not a supported value for TargetPlatformVersion. Please change it on the Project Property page. [D:\MyApp\platforms\windows\CordovaApp.Windows10.jsproj]
No valid MSBuild was detected for the selected target: Error: C:\Program Files (x86)\Programming\Microsoft Visual Studio 2017\MSBuild\15.0\Bin\msbuild.exe: Command failed with
 exit code 1
````

I can fix this by manually editing ````platforms\windows\CordovaApp.Windows10.jsproj```` to change this line, but I was under the impression that anything in the 'platforms' folder shouldn't be touched, as it may get replaced when building/cleaning/updating.

## Feature Description

There are various settings that can be added to ````config.xml```` that look like they should influence this, but none of them seem to resolve the issue:

````xml
        <preference name="windows-target-version" value="10.0" />
        <preference name="windows-appx-target" value="uap" />
        <preference name="windows-phone-target-version" value="10.0" />
        <preference name="windows-phone-target-platform-version" value="10.0.15063.0" />
        <preference name="Windows.Universal-MinVersion" value="10.0.15063.0" />
        <preference name="Windows.Mobile-MinVersion" value="10.0.15063.0" />
````

I would expect that using one of these settings, or a new setting for this specific purpose, would ensure the correct build is performed.

## Alternatives or Workarounds

I have been able to fix this by manually editing the file, but this doesn't appear to be a sustainable solution for the reasons given.

## Other notes

I have logged this as a feature request, but it might actually be considered a bug.

The basic issue is to provide a way to tell Visual Studio to build using the correct SDK, and as there appear to be settings to control this that aren't being applied in this instance.  If the existing settings are not working as intended, this is a bug.  If this is not currently intended to be configurable, then this is a feature request.

Or, if there is already some way to achieve this that I have been unable to find via the online documentation [1](https://cordova.apache.org/docs/en/5.1.1/guide/platforms/win8/win10-support.html), [2](https://cordova.apache.org/docs/en/latest/guide/platforms/windows/index.html#project-configuration), then perhaps this is a documentation bug.

## Config details

* Cordova 8.1.2
* Cordova-Windows 6.0.1
* Visual Studio 2017
* OS: Windows 8.1

**Comment by janpio** [comment]
Sounds valid.

If you want and can investigate this yourself, searching the codebase for either `TargetPlatformVersion` to see if _something_ might already exist or `windows-target-version` (and the others) to understand how the existing preferences work would be my first steps.

We would sure appreciate any support here, otherwise this issue will probably just sit here. Thanks!

**Comment by janpio** [comment]
I spent some time looking through code related to that, and I think you might be looking for `uap-target-min-version` and `windows-target-version` to influence these two values.

**Comment by janpio** [comment]
Ok, had some time to spend on investigating this:

> The CordovaApp.Windows10.jsproj template file has a hard-coded TargetPlatformVersion, which currently seems to be set to 10.0.10240.0

This value is not hardcoded, but gets filled by the maximum SDK installed on your machine when `cordova prepare` is run (which `cordova build` and `cordova run` do in the background):

https://github.com/apache/cordova-windows/blob/c52b81c3f6daff69b57939fcf62451d3c2a602dd/template/cordova/lib/prepare.js#L497

This means that your machine probably only had `10.0.10240.0` or no Windows SDK at all, as 10.0.10240.0 is also the default, installed.

For me the value for example is set to `<TargetPlatformVersion>10.0.18362.0</TargetPlatformVersion>` when running `cordova platform add windows`.

So installed the `10.0.15063.0` SDK should automatically replace this value.

---

If you also want to influence `TargetPlatformMinVersion` in `.jsproj`, then you can use `<preference name="uap-target-min-version" value="10.0.15063.0" />` in `config.xml`.

---

And related, you can also realize this diff:

```diff
-        <TargetDeviceFamily MaxVersionTested="10.0.10240.0" MinVersion="10.0.10240.0" Name="Windows.Universal" />
+        <TargetDeviceFamily MaxVersionTested="10.0.15063.0" MinVersion="10.0.15063.0" Name="Windows.Universal" />
```

by setting this in `config.xml`:

```
        <preference name="Windows.Universal-MinVersion" value="10.0.15063.0" />
        <preference name="Windows.Universal-MaxVersionTested" value="10.0.15063.0" />
```

Although I am not totally sure what this achieves to be honest.

---

Please let me know if this helped to fix the problem for your @MarkMaldaba.

**Comment by janpio** [comment]
Ping @MarkMaldaba

**Comment by MarkMaldaba** [comment]
Thanks for the ping.  It's on my list to test this, but haven't got to it yet.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
