### ISSUE TITLE
config-file tag removed from config.xml is not removed from appxmanifest

### ISSUE THREAD

**Issue by dominic-simplan** [apache/cordova-windows#337]
# Bug Report

### What is expected to happen?
Removing a `<config-file>` element from the config.xml should be reflected in the AppxManifest.xml / package.*.appxmanifest file after running the build command.

### What does actually happen?
Having for example this configuration in the main config.xml:
```
<platform name="windows">
        <config-file parent="/Package/Capabilities" target="package.appxmanifest">
            <Capability Name="allJoyn" />
        </config-file>
    </platform>
```

And then removing this <config-file> element and building the application with `cordova build windows -- --archs="x64"` will:
* Update the platforms\windows\config.xml correctly
* **Not remove** the according element from the platforms\windows\windows.json file
* **Not remove** the according Capability element from the package.*.appxmanifest files

### Environment, Platform, Device

Windows 10

### Version information

Cordova 8.1.2
Cordova-windows 6.0.1 and 7.0.0

Might be related to #336.
Not sure if this is a bug or if I am expected to readd the platform after making changes to the config.xml file... in case of the latter, feel free to close these two issues...

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
Will try to reproduce and report back.

**Comment by janpio** [comment]
Similar to https://github.com/apache/cordova-windows/issues/336 I can also not reproduce this: https://github.com/apache/cordova-windows/issues/336#issuecomment-508737522

`platforms/windows/windows.json` has some leftovers of the munges, but that seems harmless:

```
    "files": {
      "package.phone.appxmanifest": {
        "parents": {
          "/Package/Capabilities": []
        }
      },
      "package.windows.appxmanifest": {
        "parents": {
          "/Package/Capabilities": []
        }
      },
      "package.windows10.appxmanifest": {
        "parents": {
          "/Package/Capabilities": []
        }
      }
    }
```

(Again, using Cordova CLI 9 for testing.)

**Comment by janpio** [comment]
Ping @dominic-simplan

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
