### ISSUE TITLE
Use `vswhere` for better Visual Studio and MSBuildTools detection

### ISSUE THREAD

**Issue by janpio** [apache/cordova-windows#344]
Microsoft added `vswhere` to the default install of Visual Studio 2017:
https://github.com/Microsoft/vswhere
https://github.com/Microsoft/vswhere/wiki/Find-MSBuild
https://docs.microsoft.com/en-us/visualstudio/install/tools-for-managing-visual-studio-instances
https://blogs.msdn.microsoft.com/heaths/2017/04/21/vswhere-is-now-installed-with-visual-studio-2017/

We already use it in `appveyor.yml` to debug output these paths for the CI environment. It would be handy to also use this simple command in `MSBuildTools.js` and similar code instead of what is currently there (which is really confusing and party bad).

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
