### ISSUE TITLE
Windows 10 Min Version Must Be Configured Twice in Config.xml

### ISSUE THREAD

**Issue by janpio** [apache/cordova-windows#346]
[Originally reported in https://issues.apache.org/jira/browse/CB-13917 ]

In config.xml, the minimum Windows 10 version preference must be set with both:

```
  uap-target-min-version
  Windows.Universal-MinVersion
```

Setting `uap-target-min-versio` results in the value being copied to `CordovaApp.Windows10.jsproj`.

Setting `Windows.Universal-MinVersion` results in the value being copied to `package.windows10.appxmanifest`.

If `uap-target-min-version` is not set, the minimum version of the app in the Microsoft Store is incorrect.

Development of Windows 10 apps would be simplified by only having to set the minimum version in one place.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
