### ISSUE TITLE
(Re)move `cordova-windows10.md`

### ISSUE THREAD

**Issue by janpio** [apache/cordova-windows#347]
https://github.com/apache/cordova-windows/blob/master/cordova-windows10.md

> *This document contains information about an experimental branch of cordova-windows with support for 
> Windows 10 Technical Preview 2 released at the Build conference in April 2015.  Information is subject 
> to change with later revisions of the software.*

This is definitely not true any more. The file should be removed and the information in it, if still relevant, moved to the docs.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
