### ISSUE TITLE
Add support for Edge Dev as the HTML engine

### ISSUE THREAD

**Issue by trajano** [apache/cordova-windows#362]
# Feature Request

Add support for Edge Dev as the HTML engine instead of the normal Edge.

## Motivation Behind Feature

* Support for Transparent WEBM videos.

## Feature Description

There should be an option to select an alternate rendering engine for Windows rather than the Edge browser.

## Alternatives or Workarounds

Use Electron, but you lose the Windows App look and feel

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
