### ISSUE TITLE
CordovaApp.Windows10.jsproj Path to MsBuild wrong

### ISSUE THREAD

**Issue by UlrichGiorgioJaeger** [apache/cordova-windows#363]
# Bug Report   

Wrong Path to MSBuild Files 

##CordovaApp.Windows10.jsproj(61,5):      <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\$(WMSJSProjectDirectory)\Microsoft.VisualStudio.$(WMSJSProject).Default.props" />

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
