### ISSUE TITLE
JavaScript UWP development from VS 2019 not supported

### ISSUE THREAD

**Issue by coolaij** [apache/cordova-windows#364]
# Bug Report
JavaScript UWP development from Visual Studio 2019 not supported. Can't open created visual studio project by cordova. JavaScript UWP development does not support any more by visual studio

## Problem
JavaScript UWP development from Visual Studio 2019 not supported. Can't open created visual studio project by cordova. JavaScript UWP development does not support any more by visual studio

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
See #327
