### ISSUE TITLE
Can't cordova build or run platform windows with Visual Studio 2017

### ISSUE THREAD

**Issue by 00King00** [apache/cordova-windows#369]
# Bug Report

## Problem
I can't build windows platform with the command "cordova build windows".

When I type command "cordova build windows or ionic cordova build windows or run windows". I received:
Error Information:
ENV var MSBUILDDIR is set C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
Building project: E:\Bitbucket\bettingods-app-ionic\platforms\windows\CordovaApp.Windows10.jsproj
        Configuration : debug
        Platform      : anycpu
        Buildflags    : /p:AppxBundle=Never
        MSBuildTools  : C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
buildProject spawn: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild [ 'E:\\Bitbucket\\bettingods-app-ionic\\platforms\\windows\\CordovaApp.Windows10.jsproj',
  '/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal',
  '/nologo',
  '/p:Configuration=debug',
  '/p:Platform=anycpu',
  '/p:AppxBundle=Never' ] { stdio: 'inherit' }
  prebuild.js: Patching platform `10`
  - Injected `base.js` reference to `/www/index.html`
  - Removing /( *)(<script\s+(?:type="text\/javascript"\s+)?src="\/\/Microsoft.WinJS.2.0\/js\/base.js">\s*<\/script>)(\s*)/ from /www/index.html
  - Removing /( *)(<script\s+(?:type="text\/javascript"\s+)?src="\/\/Microsoft.Phone.WinJS.2.1\/js\/base.js">\s*<\/script>)(\s*)/ from /www/index.html
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(780,5): error : The OutputPath property is not set for project 'SQLite
3.UWP.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='debug'  Platform='Win32'.  You may be
seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [E:\Bi
tbucket\bettingods-app-ionic\plugins\cordova-sqlite-storage\src\windows\SQLite3-WinRT-sync\SQLite3\SQLite3.UWP.vcxproj]
No valid MSBuild was detected for the selected target: Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild: Command failed with exit code 1

My Version information:
Ionic:

   Ionic CLI          : 5.2.4 (C:\Users\User\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, windows 7.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, (and 17 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.9

System:

   Android SDK Tools : 26.1.1 (C:\Users\User\AppData\Local\Android\Sdk)
   NodeJS            : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

**Comment by brodybits** [comment]
From the error message I see that the issue is with SQLite plugin and not cordova-windows itself. Please raise the issue there (I happen to maintain that one). A [minimal, reproducible example ([1])](https://stackoverflow.com/help/minimal-reproducible-example) would really help get to the bottom of your issue.

[1] https://stackoverflow.com/help/minimal-reproducible-example

**Comment by VitorBras** [comment]
Hey man, What is cordova-windows? 
I installed Visual Studio 2019 and Visual studio 2015. I tried run and build my cordova project to Windows Ten but i has a error. APPX050. I just created a simple cordova project and tried run this in local machine but i cant do that. Can you explain what is cordova-windows? I guess that is a tool to develop windows applications with Cordova. 

Now, i have Cordova normally.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
