### ISSUE TITLE
META: start major release 8.0.0 with some breaking changes

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-windows#373]
- drop support for Node.js < 10
- drop support for Windows 8.1 & Windows Phone 8.1, as I proposed in PR #371
- use @cordova/eslint-config (issue #370)
- _update eslint and other devDependencies_
- hopefully drop use of Q
- consider better spawn implementation as discussed in cordova-common
- _ideally phase out use of shelljs_
- _check for any outdated package dependencies such as `semver`_
- consider any other possible cleanup

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
