### ISSUE TITLE
Can we use target minimum windows SDK version 10.0.16299.0

### ISSUE THREAD

**Issue by tilakraok** [apache/cordova-windows#382]
I have created a sample application with minimum windows SDK version **10.0.10240.0** and I was able to call the native plugin in windows runtime component.
I tried to integrate **Lucenenet**(Only latest beta is supported by UWP app) with the project and that requires **10.0.16299.0**.
After integration, Native plugins which were working previously started throwing "Unknown runtime error".

What is causing that runtime error?

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
