### ISSUE TITLE
Using Chrome-based webview as rendering backend for Cordova for Windows instead of EdgeHTML

### ISSUE THREAD

**Issue by FabriceFR** [apache/cordova-windows#386]
# Feature Request

## Motivation Behind Feature
Is it planned that Cordova for Windows will use Chrome-based webview as rendering backend?
According to [microsoft/vscode-cordova], this support is expected to allow to compile on windows platform using VS Studio code with the latest cordova versions as a replacement of VS2017.

## Feature Description
Cordova for Windows use Chrome-based webview as rendering backend instead of EdgeHTML Edge whose support will end on March 9 2021 and which is not supported by vscode-cordova 

## Alternatives or Workarounds
Use of VS2017 with old versions of cordova for windows platform & use of VSCode for iOS and Android recent generations support

**Comment by coolscene** [comment]
The correct way to support the new chrome based webview2 would be to create a new cordova platform as it is completely different. Cordova plugins would then have to add support to the new Windows platform as code would have to be written much like Android plugins are with C#/VBasic code that interacts with the webview using messages between each other.

The new Edge can now be integrated with UWP/WinUI and is shipped starting with Windows 10 version 20H1 (build 19042) which means this new cordova platform would only support that version an up. At the time of this post, it seems there is no support for Xbox yet so apps developed for this platform would not support Xbox until Microsoft updates it.

More info:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms
https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui

Everything still seems very early on Microsoft side but would be nice to know if there any plans to support the new Windows development environment.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
