### ISSUE TITLE
comma as decimal separator on ```<input type="number"> ```

### ISSUE THREAD

**Issue by ksch10bob** [apache/cordova-windows#390]
# Bug Report
## Problem
When i use comma as decimal seperator on ```<input type="number"> ``` lets say 23,1  the input fields value is an empty string.
### What is expected to happen?
value = "23.1"
valueAsNumber = 23.1

### What does actually happen?

value =""
valueAsNumber = NaN

## Information
* simple hello cordova app
* add input field with type number to index.html
* run in debug mode and evalute value and valueAsNumber 

### Environment, Platform, Device
Operating System: Windows 10 Pro, 20H2, 19042.746
Device : Lenovo Thinkpad E485

### Version information
Cordova 10.0.0
cordova-windows: 7.0.1
Build-target: windows 10 (x64)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
