### ISSUE TITLE
The following navigation rule had an invalid URI scheme and will be ignored: "*".

### ISSUE THREAD

**Issue by ugale-deepak3010** [apache/cordova-windows#392]
# Bug Report

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
