### ISSUE TITLE
Microsoft Surface hybrid touch events

### ISSUE THREAD

**Issue by corentin-begne** [apache/cordova-windows#394]
# Bug Report

## Problem
Touch events are not fired correctly

### What is expected to happen?
Moving camera in webgl using touch on screen

### What does actually happen?
Not any touch events are fired, only mouse and mouse down, few mouse move then nothing, no mouse up.
If I touch without moving mouse up is fired.

## Information

Same site on web work correctly with the same device.

### Environment, Platform, Device

Microsoft Surface hybrid computer 

### Version information

Cordova 10.0.0
cordova-windows 8.0.0-dev
Windows 10

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
