### ISSUE TITLE
Running HelloWorld throws an error

### ISSUE THREAD

**Issue by mysorian** [apache/cordova-windows#400]
# Bug Report

## Problem
The example HelloWorld (for Android) produces no error but produces an .html on an Oracle site.

### What is 

expected to happen?
Not sure what should happen. Expected a display which would show the result

### What does actually happen?
Failed building the gradle.

## Information

Java is not installed on the machine. Opening this in Android Studio Snow Cat and building produces this build error (see image).
Is it possible to remove the highlighted portion and build?(see image)

![andstd_error](https://user-images.githubusercontent.com/5265734/139968295-7a0bb9e9-4234-420c-91a9-d9632eda5fae.jpg)

![andstd_error2](https://user-images.githubusercontent.com/5265734/139968324-fc49d645-a830-447c-9c57-5a3a91b15336.jpg)
### Command or Code

No error using the command to run 

### Environment, Platform, Device

Windows 10(x64). 

### Version information

Cordova 10.0
Android Studio

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by mysorian** [comment]
Just realized it is not an Cordova bug. It's just the Android Studio is not configured to run this.
Thanks

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
