### ISSUE TITLE
package.windows10.appxmanifest does not set the correct descriptions as in config.xml

### ISSUE THREAD

**Issue by pjc2007** [apache/cordova-windows#401]
# Bug Report

## Problem
No matter what I do, the Cordova package manifest always ends up with the description "A sample Apache Cordova application that responds to the deviceready event." instead of what I put in config.xml.

I even ran a node script to replace the 2 description tags in package.windows10.appxmanifest, and an extra entry in the generated config.xml, but after I build the above description just comes back!

### What is expected to happen?
Just pick up and use the description as in the source config.xml

### What does actually happen?
It always replaces all the descriptions with "A sample Apache Cordova application that responds to the deviceready event." 

### Environment, Platform, Device
Ionic UWP,  building on Windows 10 Cordova version 10.0.0

### Version information
```
ionic  info

Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\peter\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.13
   @angular-devkit/build-angular : 0.803.29
   @angular-devkit/schematics    : 8.3.29
   @angular/cli                  : 8.2.2
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, windows 7.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 14 other plugins)

Utility:

   cordova-res : 0.15.3
   native-run  : 0.2.9

System:

   Android SDK Tools : 26.1.1 (C:\Users\peter\AppData\Local\Android\sdk)
   NodeJS            : v14.17.0 (C:\Program Files\nodejs\node.exe)
   npm               : 7.21.1
   OS                : Windows 10
```

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
