### ISSUE TITLE
instructions from https://cordova.apache.org for platform Windows erroneous

### ISSUE THREAD

**Issue by via-lars** [apache/cordova-windows#402]
# Bug Report

### What is expected to happen?

step 4 is run

### What does actually happen?

an error message occurs:

`MSBuild v4.0 is not supported, aborting.
No valid MSBuild was detected for the selected target: AppPackages folder doesn't exist`

## Information

follow the instructions from https://cordova.apache.org for platform `windows`

### Command or Code

` cordova run windows`

### Environment, Platform, Device

windows (10 x64)

### Version information

as of 12/14/21 2 pm cet

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

x I hope so

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
