### ISSUE TITLE
The processor architecture of your project 'arm' doesn’t match the processor architecture 'x86' of the referenced project 'SQLite3.UWP'.

### ISSUE THREAD

**Issue by pjc2007** [apache/cordova-windows#403]
# Bug Report

## Problem
I have been building my Ionic Cordova windows application for a number of years now. A always build x86, x64, and ARM. All of a sudden, with no source changes on my behalf at all, the ARM build will not work.

It is now getting the following error
```
Error	APPX0505	The processor architecture of your project 'arm' doesn’t match the processor architecture 'x86' of the referenced project 'SQLite3.UWP'. Change the targeted processor architectures to align between your project and its references.	CordovaApp.Windows10	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets
```
The SQLite plugin project is C++, and there just is no option for ARM

![image](https://user-images.githubusercontent.com/10663978/147726934-46db60ec-e5ed-4fc5-abbf-89b2816aca45.png)

I can't go back to when it was building, as there has been no changes on my behalf, I do not keep the files created by adding the platform in source control (it is just an artifact  of the build).

Ir was building around a month ago, I have just notices my ARM build is onw missing for the last few builds (again with no cahnges at all on my behalf)

### What is expected to happen?
Would like to be able to build for ARM again

### What does actually happen?
The build for ARM now fails with the above APPX0505, and nothing I do can fix it. This happens on both the build machine and my local dev machine. It use to build on both. I have always used the SQLite plugin, I do not understand what could have changed,

### Command or Code

```
ionic cordova build windows --prod --release -- --archs=\"x86 x64 arm\" --buildConfig=platform_build_files\\windows\\build.json
```
or just building from Visual Studio.

### Environment, Platform, Device
From Ionic diagnostics
```
$ ionic info

Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\pchapman\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.13
   @angular-devkit/build-angular : 0.803.29
   @angular-devkit/schematics    : 8.3.29
   @angular/cli                  : 8.2.2
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : android 10.1.1, ios 6.2.0, windows 7.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 15 other plugins)

Utility:

   cordova-res : 0.15.3
   native-run  : 0.2.9

System:

   Android SDK Tools : 26.1.1 (C:\Users\pchapman\AppData\Local\Android\sdk)
   NodeJS            : v14.17.0 (C:\Program Files\nodejs\node.exe)
   npm               : 7.21.1
   OS                : Windows 10
```

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
